spring.profiles.active=@spring.profiles.active@

server.port=8083

spring.application.name=stripe-provider-service
stripe.api.key=USE YOUR OWN STRIPE SECRET KEY BY CREATING A STRIPE ACCOUNT
stripe.create-session-url= https://api.stripe.com/v1/checkout/sessions
stripe.get-session-url= https://api.stripe.com/v1/checkout/sessions/{id}
stripe.expire-session-url= https://api.stripe.com/v1/checkout/sessions/{id}/expire
stripe.invoice-url= https://api.stripe.com/v1/checkout/sessions/{id}?expand[]=invoice


spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=llama3.2:1b

stripe.webhook.secret=FIND YOUR OWN AND USE YOUR USE

processing.notification.url=http://localhost:8082/v1/payments/notifications


# ========= Eureka Client Configuration =========
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}

