spring.profiles.active=@spring.profiles.active@

server.port=8083

spring.application.name=stripe-provider-service
stripe.api.key=sk_test_51S0btHEHK3N4K2glRwvv3GGoAEEPE0BD1SvwjPrfrp3Mwzxl2Kd2wVIOkSZxrF8I1ZW9tVqzArGzckfZykrVZRUB004IR8U2br
stripe.create-session-url= https://api.stripe.com/v1/checkout/sessions
stripe.get-session-url= https://api.stripe.com/v1/checkout/sessions/{id}
stripe.expire-session-url= https://api.stripe.com/v1/checkout/sessions/{id}/expire
stripe.invoice-url= https://api.stripe.com/v1/checkout/sessions/{id}?expand[]=invoice


spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=llama3.2:1b

stripe.webhook.secret=whsec_3a3e205d3d8317657f4d2da2a9df296ce06b9482b6c69ffa864eea9de4bb3ff6

processing.notification.url=http://localhost:8082/v1/payments/notifications


# ========= Eureka Client Configuration =========
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}

